# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kidsnote_Pre_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kidsnote_Pre_Project
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReactorKit'

end
